metaflop:
  font_otf: 'timeout %{timeout} ./mf2outline --encoding=t1 --copyright="Copyright (c) %{year}, Metaflop (http://www.metaflop.com), Simon Egli, Marco Mueller, Alexis Reigel, with Reserved Font Name %{fontface}. Dual licensed under the GPL v3 (http://www.gnu.org/copyleft/gpl.html) and the OFL v1.1 (http://scripts.sil.org/OFL_web)." --family=%{fontface} --fullname="%{fontface} %{font_hash}" --fontname="%{fontface}-%{font_hash}" --vendor=flop --formats=otf,ttf,svg font.mf'

  font_web: sfnt2woff font.otf && ttf2eot font.ttf > font.eot

metafonts:
  adjuster:
    description: <a href="/modulator?fontface=Adjuster">MF Adjuster</a>, a basic form,
      highly functional, almost crystalline. It follows a strict grid and a simple no-curves policy
      and it comes along with a reduced set of parameters.
      The font's sophistication derives from the angle and pen parameter (circle, square or razor).
      The font encoding of MF Adjuster covers 256 characters supporting many european languages
      with latin writing.
    type_designer:
      -
        name: Marco Müller
        url: http://www.marco-mueller.com/
      -
        name: Simon Egli
        url: http://www.simonegli.com/
    year: 2012
    encoding: T1
    source_code:
      -
        title: Github
        url: https://github.com/metaflop/metaflop-font-adjuster
    images:
      -
        - adjuster1-01.png
        -
      -
        - adjuster1-02.png
        -
      -
        - adjuster1-03.png
        -
      -
        - adjuster1-04.png
        - The 256 characters of T1 font encoding.
      -
        - adjuster1-05.png
        - MF Adjuster supporting many european languages with latin writing.
      -
        - adjuster1-06.png
        - Transformation of the Angle parameter.
      -
        - adjuster2-01.png
        - Angle transformation from 90 to 15 degree and vice versa.
      -
        - adjuster2-02.png
        - Pen Width transformation from 2.0 to 0.05 points and vice versa.
      -
        - adjuster2-03.png
        - Unit width transformation from 0.2 to 5.0 points.
      -
        - adjuster2-04.png
        - Unit width transformation from 5.0 to 0.2 points.
      -
        - adjuster2-05.png
        - Pen Razor transformation from 0 to 45 degree and vice versa.
    subimages:
      -
        - adjuster-derivations-01.png
        - 4pY8SPVUeO
      -
        - adjuster-derivations-02.png
        - GfXF00-goL
      -
        - adjuster-derivations-03.png
        - pQkUOJOPk8
      -
        - adjuster-derivations-04.png
        - WitXxEC_wq
      -
        - adjuster-derivations-05.png
        - 19mOboz6Sq
      -
        - adjuster-derivations-06.png
        - B_DF7u3XWz
      -
        - adjuster-derivations-07.png
        - JgRFUo8ZJV
      -
        - adjuster-derivations-08.png
        - BL4uWv2Vdt
      -
        - adjuster-derivations-09.png
        - xo_LzNRVdV
      -
        - adjuster-derivations-10.png
        - poimn57bWc
      -
        - adjuster-derivations-11.png
        - N-SDv-KkDl
      -
        - adjuster-derivations-12.png
        - IVhW3c2vuS
  bespoke:
    description: <a href="/modulator?fontface=Bespoke">MF Bespoke</a> is geared to simply
      constructed sans serif fonts. This metafont consists of 14 adjustable parameters grouped
      in classes of dimension, proportion and shape.
      By using this range of parameters a high variety of derivates can be achieved.
      The standard font and font-box has the size of 10 unit points.
    type_designer:
      -
        name: Marco Müller
        url: http://www.marco-mueller.com/
      -
        name: Simon Egli
        url: http://www.simonegli.com/
    year: 2012
    encoding: '-'
    source_code:
      -
        title: Github
        url: https://github.com/metaflop/metaflop-font-bespoke"
    images:
      -
        - bespoke1-01.png
        - Construction of MF Bespoke using base points and geometrical relations.
      -
        - bespoke1-02.png
        - Construction of MF Bespoke using base points and geometrical relations.
      -
        - bespoke1-03.png
        - Construction of MF Bespoke using base points and geometrical relations.
      -
        - bespoke1-04.png
        -
      -
        - bespoke1-05.png
        -
      -
        - bespoke1-06.png
        -
      -
        - bespoke1-07.png
        - 'Transformation of single parameters – dimension, proportion and shape.'
      -
        - bespoke2-01.png
        - Superness curve transformation from 1.0 to 0.3 and vice versa.
      -
        - bespoke2-02.png
        - Contrast transformation from 18 to 1 and vice versa.
      -
        - bespoke2-03.png
        - Horizontal and vertical increase transformation from 1.0 to 0.0 points and vice versa.
      -
        - bespoke2-04.png
        - Unit width transformation from 0.2 to 5.0 points.
      -
        - bespoke2-05.png
        - Unit width transformation from 5.0 to 0.2 points.
      -
        - bespoke2-06.png
        - Horizontal and vertical increase transformation from 1.0 to 0.0 points and vice versa.
    subimages:
      -
        - bespoke-derivations-01.png
        - W2wMVl1oOf
      -
        - bespoke-derivations-02.png
        - wEEJXpb_F_
      -
        - bespoke-derivations-03.png
        - X_nuDV5EKb
      -
        - bespoke-derivations-04.png
        - xQZl0I4bG4
      -
        - bespoke-derivations-05.png
        - bBv88L09e8
      -
        - bespoke-derivations-06.png
        - f0ySyHr68Q
      -
        - bespoke-derivations-07.png
        - bQCd3GYPgX
      -
        - bespoke-derivations-08.png
        - Hb-V8s8C70
      -
        - bespoke-derivations-09.png
        - jVzgqoraQu
      -
        - bespoke-derivations-10.png
        - L9JtCtna31
      -
        - bespoke-derivations-11.png
        - tRp6NK0eyw
      -
        - bespoke-derivations-12.png
        - UcH5rxsNVi
  fetamont:
    description: <a href="/modulator?fontface=Fetamont">MF Fetamont</a> is an extended version of
      Knuth's rounded elliptical logo font.
      The 11 parameters, including superness, slanting and randomness,
      enlarge the logo font to a complete typeface with a high variety of derivates.
      The font covers capital letters and small caps with a T1 encoding of 256
      characters supporting many european languages with latin writing.
    type_designer:
      -
        name: Linus Romer
        url: http://www.ctan.org/author/romer
    year: 2014
    encoding: T1
    source_code:
      -
        title: Github
        url: https://github.com/metaflop/metaflop-font-fetamont
      -
        title: CTAN
        url: http://www.ctan.org/tex-archive/fonts/fetamont
    images:
      -
        - fetamont-01.png
        -
      -
        - fetamont-02.png
        - The 256 characters of T1 font encoding.
      -
        - fetamont-03.png
        -
      -
        - fetamont-04.png
        - MF Fetamont supporting many european languages with latin writing.
      -
        - fetamont-05.png
        -
      -
        - fetamont-06.png
        -
    subimages:
      -
        - fetamont-derivations-01.png
        - GkBrVZN_iX
      -
        - fetamont-derivations-02.png
        - MfkdNdMDDn
      -
        - fetamont-derivations-03.png
        - dl7Ht74V5u
      -
        - fetamont-derivations-04.png
        - LkeR_2xby-
      -
        - fetamont-derivations-05.png
        - PP_OiCwdeP
      -
        - fetamont-derivations-06.png
        - 27bdRg9sxs
      -
        - fetamont-derivations-07.png
        - 9ExkzVmc3w
      -
        - fetamont-derivations-08.png
        - -VD4YZ2DoE
      -
        - fetamont-derivations-09.png
        - hCBJISerqx
      -
        - fetamont-derivations-10.png
        - Lib0ZSdIQq
      -
        - fetamont-derivations-11.png
        - lIyb2HtLTh
      -
        - fetamont-derivations-12.png
        - e93KUT9DBj
      -
        - fetamont-derivations-13.png
        - 6vxhO7I2He
      -
        - fetamont-derivations-14.png
        - aqgUyrHqrz
      -
        - fetamont-derivations-15.png
        - -G_AJAvhEX
      -
        - fetamont-derivations-16.png
        - dFcZJbTYmO
      -
        - fetamont-derivations-17.png
        - MelgMG3dUD
      -
        - fetamont-derivations-18.png
        - ei9rUTPryF
      -
        - fetamont-derivations-19.png
        - dJCvFHU3OR
